# -*- coding: utf-8 -*-
"""disease_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ_4Aju56uNNHhjjYrNpRBH5hzbLFVoO
"""

# !pip install -q \
# tensorflow \
# scikit-learn \
# numpy \
# matplotlib \
# seaborn \
# pandas \
# streamlit \
# librosa

"""**1. Importing Libraries**"""

import tensorflow as tf
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import librosa
from tensorflow.keras.layers import Conv2D, Dense , MaxPooling2D , Flatten
from tensorflow.keras.models import Sequential
print("TensorFlow:", tf.__version__)
print("Scikit-learn:", sklearn.__version__)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

"""**2. Data Preprocessing**

Training Image Preprocessing
"""

training_dataset=tf.keras.utils.image_dataset_from_directory(
    '/content/PlantDataset/train',
    labels="inferred", # inferred means that labels are generated from the directory structure
    label_mode="categorical", # means there are so many categories if there would be two class then mode is binary
    class_names=None, #since categorical so no need to give explicitly
    color_mode="rgb",
    batch_size=32, # if number increased traing will be fast but last precision (feed only 32 training example to nn at a time)
    image_size=(128, 128), #resize the image
    shuffle=True,   #to reduce biasness of model
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    format="tf",
    verbose=True,
)

"""Validation Image Preprocessing"""

validation_dataset=tf.keras.utils.image_dataset_from_directory(
    '/content/PlantDataset/valid',
    labels="inferred", # inferred means that labels are generated from the directory structure
    label_mode="categorical", # means there are so many categories
    class_names=None, #since categorical so no need to give explicitly
    color_mode="rgb",
    batch_size=32, # if number increased traing will be fast but last precision
    image_size=(128, 128), #resize the image
    shuffle=True,   #to reduce biasness of model
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    format="tf",
    verbose=True,
)

"""**Convolution** (used to extract feature map) is a process where a small filter (also called a kernel) moves over an image to find important features

--> It uses **Kernel** typically of size 3*3 that scans the 2d matrix of image and extracts its important features

--> **Stride** is process involved that determines the step to be taken by kernel

--> **Pooling** is process of reducing size of image by keeping the important features and removing unnecessary details.

**Max Pooling** extracts the maximum value from the kernel size

**Average Pooling** extracts the maximum value from the kernel size

**Flatening** ---> then 2d matrix is converted into 1d matrix and passed into nn for further calculations

**3. Building Model**
"""



model = Sequential()

"""----> Building Convolution Layer"""

model.add(Conv2D(filters=32 , kernel_size=3 ,padding='same' ,activation='relu' , input_shape =[128,128,3]))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=32 , kernel_size=3 ,padding='same' ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=64 , kernel_size=3 ,padding='same' ,activation='relu' , input_shape =[128,128,3]))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=64 , kernel_size=3 ,padding='same' ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=128 , kernel_size=3 ,padding='same' ,activation='relu' , input_shape =[128,128,3]))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=128 , kernel_size=3 ,padding='same' ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=256 , kernel_size=3 ,padding='same' ,activation='relu' , input_shape =[128,128,3]))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=256 , kernel_size=3 ,padding='same' ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

"""----> Flatening and passing it to hidden layers"""

model.add(Flatten())
model.add(Dense(units=1024 , activation='relu'))

"""-----> Output layer"""

model.add(Dense(units=38 ,activation='softmax')) # hidden layer --> choose softmax so that it give probability of each class in each neuron and choose neurons 38 bcz total number of outputs are 38(classes)

"""----> Compiling Model"""

model.compile(optimizer='adam' ,loss='categorical_crossentropy' , metrics=['accuracy'])

model.summary()

"""**4. Training Model**"""

traing_history = model.fit(x=training_dataset , validation_data= validation_dataset ,epochs=10)

"""**5. Model Evaluation**

Model Evaluation on training set
"""

train_loss , train_acc = model.evaluate(training_dataset)

"""Model Evaluation on Validation set"""

val_loss , val_acc = model.evaluate(validation_dataset)

"""**6. Saving Model**"""

model.save("crop_disease_predictior_model.keras")

traing_history.history

"""Recording training history in json format"""

import json
with open("crop_disease_predictior_history.json",'w') as f:
  json.dump(traing_history.history , f)

"""**7. Accuracy Visualization**"""

epochs = [i for i in range(1,11)]
plt.plot(epochs , traing_history.history['accuracy'] , label='Training Accuracy' , color='red')
plt.plot(epochs , traing_history.history['val_accuracy'] , label='Validation Accuracy' , color='blue')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Visualization of Training and Validation Accuracy')
plt.show()

class_name = validation_dataset.class_names
class_name

test_dataset=tf.keras.utils.image_dataset_from_directory(
    '/content/PlantDataset/valid',
    labels="inferred", # inferred means that labels are generated from the directory structure
    label_mode="categorical", # means there are so many categories
    class_names=None, #since categorical so no need to give explicitly
    color_mode="rgb",
    batch_size=32, # if number increased traing will be fast but last precision
    image_size=(128, 128), #resize the image
    shuffle=False,   #to reduce biasness of model
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    format="tf",
    verbose=True,
)