# -*- coding: utf-8 -*-
"""disease_predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yJ_4Aju56uNNHhjjYrNpRBH5hzbLFVoO
"""

# !pip install -q \
# tensorflow \
# scikit-learn \
# numpy \
# matplotlib \
# seaborn \
# pandas \
# streamlit \
# librosa

"""importing dataset from drive and extracting it and arranging it into folders , train , valid , test"""
from tensorflow.keras.layers import Conv2D, Dense , MaxPooling2D , Flatten , Dropout
from tensorflow.keras.models import Sequential

from google.colab import drive
drive.mount('/content/drive')

import zipfile

zip_path = "/content/drive/MyDrive/archive.zip"
extract_path = "/content/dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction complete!")


import shutil
import os

# Move train
shutil.move(
    "/content/dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train",
    "/content/dataset/train"
)

# Move valid
shutil.move(
    "/content/dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/valid",
    "/content/dataset/valid"
)

# Move test
shutil.move(
    "/content/dataset/test/test",
    "/content/dataset/test_temp"
)

# Rename test_temp to test
os.rmdir("/content/dataset/test")
os.rename("/content/dataset/test_temp", "/content/dataset/test")

import shutil

shutil.rmtree("/content/dataset/New Plant Diseases Dataset(Augmented)")
shutil.rmtree("/content/dataset/new plant diseases dataset(augmented)")

"""**1. Importing Libraries**"""

import tensorflow as tf
import sklearn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import librosa

print("TensorFlow:", tf.__version__)
print("Scikit-learn:", sklearn.__version__)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

"""**2. Data Preprocessing**

Training Image Preprocessing
"""

training_dataset=tf.keras.utils.image_dataset_from_directory(
    '/content/dataset/train',
    labels="inferred", # inferred means that labels are generated from the directory structure
    label_mode="categorical", # means there are so many categories if there would be two class then mode is binary
    class_names=None, #since categorical so no need to give explicitly
    color_mode="rgb",
    batch_size=32, # if number increased traing will be fast but last precision (feed only 32 training example to nn at a time)
    image_size=(128, 128), #resize the image
    shuffle=True,   #to reduce biasness of model
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    format="tf",
    verbose=True,
)

"""Validation Image Preprocessing"""

validation_dataset=tf.keras.utils.image_dataset_from_directory(
    '/content/dataset/valid',
    labels="inferred", # inferred means that labels are generated from the directory structure
    label_mode="categorical", # means there are so many categories
    class_names=None, #since categorical so no need to give explicitly
    color_mode="rgb",
    batch_size=32, # if number increased traing will be fast but last precision
    image_size=(128, 128), #resize the image
    shuffle=True,   #to reduce biasness of model
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    format="tf",
    verbose=True,
)

"""**Convolution** (used to extract feature map) is a process where a small filter (also called a kernel) moves over an image to find important features

--> It uses **Kernel** typically of size 3*3 that scans the 2d matrix of image and extracts its important features

--> **Stride** is process involved that determines the step to be taken by kernel

--> **Pooling** is process of reducing size of image by keeping the important features and removing unnecessary details.

**Max Pooling** extracts the maximum value from the kernel size

**Average Pooling** extracts the maximum value from the kernel size

**Flatening** ---> then 2d matrix is converted into 1d matrix and passed into nn for further calculations

**To overcome overshooting problems**



1.   choose small learning rate like change 0.001 to 0.0001
2.   there may be underfitting so increase number of neurons
3.   adding more convolution layer to extract more features from image

**3. Building Model**
"""



model = Sequential()

"""----> Building Convolution Layer"""

model.add(Conv2D(filters=32 , kernel_size=3 ,padding='same' ,activation='relu' , input_shape =[128,128,3]))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=32 , kernel_size=3 ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=64 , kernel_size=3 ,padding='same' ,activation='relu' ))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=64 , kernel_size=3 ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=128 , kernel_size=3 ,padding='same' ,activation='relu'))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=128 , kernel_size=3 ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=256 , kernel_size=3 ,padding='same' ,activation='relu'))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=256 , kernel_size=3 ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=256 , kernel_size=3 ,padding='same' ,activation='relu'))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=256 , kernel_size=3 ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Conv2D(filters=512 , kernel_size=3 ,padding='same' ,activation='relu'))  # creating kernel size of 3 for making 32 feature map
model.add(Conv2D(filters=512 , kernel_size=3 ,padding='same' ,activation='relu'))
model.add(MaxPooling2D(pool_size=2 ,strides=2))

model.add(Dropout(0.25)) #to avoid overfitting we are dropping 25% neurons from layers

"""----> Flatening and passing it to hidden layers"""

model.add(Flatten())
model.add(Dense(units=1500 , activation='relu'))   # number of neuron is set to 1500

model.add(Dropout(0.4))

"""-----> Output layer"""

model.add(Dense(units=38 ,activation='softmax')) # hidden layer --> choose softmax so that it give probability of each class in each neuron and choose neurons 38 bcz total number of outputs are 38(classes)

"""----> Compiling Model"""

model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001,) ,loss='categorical_crossentropy' , metrics=['accuracy'])

model.summary()

"""**4. Training Model**"""

traing_history = model.fit(x=training_dataset , validation_data= validation_dataset ,epochs=10)

"""**5. Model Evaluation**

Model Evaluation on training set
"""

train_loss , train_acc = model.evaluate(training_dataset)

"""Model Evaluation on Validation set"""

val_loss , val_acc = model.evaluate(validation_dataset)

"""**6. Saving Model**"""

model.save("new_crop_disease_predictior_model.keras")

traing_history.history

"""Recording training history in json format"""

import json
with open("new_crop_disease_predictior_history.json",'w') as f:
  json.dump(traing_history.history , f)

"""**7. Accuracy Visualization**"""

epochs = [i for i in range(1,11)]
plt.plot(epochs , traing_history.history['accuracy'] , label='Training Accuracy' , color='red')
plt.plot(epochs , traing_history.history['val_accuracy'] , label='Validation Accuracy' , color='blue')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.title('Visualization of Training and Validation Accuracy')
plt.show()

class_name = validation_dataset.class_names
class_name

test_dataset=tf.keras.utils.image_dataset_from_directory(
    '/content/dataset/valid',
    labels="inferred", # inferred means that labels are generated from the directory structure
    label_mode="categorical", # means there are so many categories
    class_names=None, #since categorical so no need to give explicitly
    color_mode="rgb",
    batch_size=32, # if number increased traing will be fast but last precision
    image_size=(128, 128), #resize the image
    shuffle=False,   #to reduce biasness of model
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    format="tf",
    verbose=True,
)

y_pred = model.predict(test_dataset)
y_pred

"""Selecting class with maximum probability"""

predicted_categories = tf.argmax(y_pred,axis=1)  # axis=1 means iterate column wise

predicted_categories

true_categories= tf.concat([y for x,y in test_dataset], axis=0)    #axis=0 means iterate row wise

true_categories

y_true = tf.argmax(true_categories,axis=1)
y_true

"""Calculate precision recall"""

from sklearn.metrics import classification_report , confusion_matrix

print(classification_report(y_true, predicted_categories , target_names=class_name))

"""Now making Confusion Matrix for model

> Add blockquote

A confusion matrix is a table used to evaluate the performance of a classification model. It compares the model's predicted values against the actual (ground truth) values. This compact format quickly reveals where a machine learning algorithm is making correct predictions and where it is getting "confused
"""

cm = confusion_matrix(y_true , predicted_categories)
cm



"""Confusion Matrix Visualization"""

plt.figure(figsize=(30,30))
sns.heatmap(cm , annot=True ,annot_kws={'size':10})
plt.xlabel('Predicted class',fontsize=20)
plt.ylabel('Actual class' ,fontsize=20)
plt.title('Plant Disease Confusion Matrix',fontsize=20)
plt.show()